-- MySQL Script generated by MySQL Workbench
-- jue 04 dic 2014 10:07:58 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mahmi
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mahmi` ;

-- -----------------------------------------------------
-- Schema mahmi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mahmi` DEFAULT CHARACTER SET utf8mb4 ;
USE `mahmi` ;

-- -----------------------------------------------------
-- Table `projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projects` ;

CREATE TABLE IF NOT EXISTS `projects` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(140) NOT NULL,
  `project_repository` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metagenomes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metagenomes` ;

CREATE TABLE IF NOT EXISTS `metagenomes` (
  `metagenome_id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `metagenome_fasta` LONGBLOB NOT NULL,
  PRIMARY KEY (`metagenome_id`),
  INDEX `fk_metagenomes_projects_idx` (`project_id` ASC),
  CONSTRAINT `fk_metagenomes_projects`
    FOREIGN KEY (`project_id`)
    REFERENCES `projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
ROW_FORMAT = COMPRESSED
KEY_BLOCK_SIZE = 16;


-- -----------------------------------------------------
-- Table `proteins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proteins` ;

CREATE TABLE IF NOT EXISTS `proteins` (
  `protein_id` INT NOT NULL AUTO_INCREMENT,
  `protein_hash` CHAR(40) NOT NULL,
  `protein_sequence` LONGBLOB NOT NULL,
  PRIMARY KEY (`protein_id`),
  UNIQUE INDEX `protein_hash_UNIQUE` (`protein_hash` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metagenome_proteins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metagenome_proteins` ;

CREATE TABLE IF NOT EXISTS `metagenome_proteins` (
  `metagenome_id` INT NOT NULL,
  `protein_id` INT NOT NULL,
  `counter` INT NOT NULL,
  PRIMARY KEY (`metagenome_id`, `protein_id`),
  INDEX `fk_metagenomes_has_proteins_proteins1_idx` (`protein_id` ASC),
  INDEX `fk_metagenomes_has_proteins_metagenomes1_idx` (`metagenome_id` ASC),
  CONSTRAINT `fk_metagenomes_has_proteins_metagenomes1`
    FOREIGN KEY (`metagenome_id`)
    REFERENCES `metagenomes` (`metagenome_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_metagenomes_has_proteins_proteins1`
    FOREIGN KEY (`protein_id`)
    REFERENCES `proteins` (`protein_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enzymes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enzymes` ;

CREATE TABLE IF NOT EXISTS `enzymes` (
  `enzyme_id` INT NOT NULL AUTO_INCREMENT,
  `enzyme_name` VARCHAR(140) NOT NULL,
  PRIMARY KEY (`enzyme_id`),
  UNIQUE INDEX `enzyme_name_UNIQUE` (`enzyme_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peptides`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peptides` ;

CREATE TABLE IF NOT EXISTS `peptides` (
  `peptide_id` INT NOT NULL AUTO_INCREMENT,
  `peptide_hash` CHAR(40) NOT NULL,
  `peptide_sequence` LONGBLOB NOT NULL,
  PRIMARY KEY (`peptide_id`),
  UNIQUE INDEX `peptide_hash_UNIQUE` (`peptide_hash` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digestions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `digestions` ;

CREATE TABLE IF NOT EXISTS `digestions` (
  `digestion_id` INT NOT NULL AUTO_INCREMENT,
  `enzyme_id` INT NOT NULL,
  `peptide_id` INT NOT NULL,
  `protein_id` INT NOT NULL,
  `counter` INT NOT NULL,
  PRIMARY KEY (`digestion_id`),
  INDEX `fk_digestions_enzymes1_idx` (`enzyme_id` ASC),
  INDEX `fk_digestions_table11_idx` (`peptide_id` ASC),
  INDEX `fk_digestions_proteins1_idx` (`protein_id` ASC),
  UNIQUE INDEX `fks_UNIQUE` (`enzyme_id` ASC, `peptide_id` ASC, `protein_id` ASC),
  CONSTRAINT `fk_digestions_enzymes1`
    FOREIGN KEY (`enzyme_id`)
    REFERENCES `enzymes` (`enzyme_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_digestions_table11`
    FOREIGN KEY (`peptide_id`)
    REFERENCES `peptides` (`peptide_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_digestions_proteins1`
    FOREIGN KEY (`protein_id`)
    REFERENCES `proteins` (`protein_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO mahmiuser;
 DROP USER mahmiuser;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'mahmiuser' IDENTIFIED BY 'mahmipass';

GRANT ALL ON * TO 'mahmiuser';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
